version: '3.4'

services:
  mymulticontainer: #comment
    image: runranweb.azurecr.io/mymulticontainer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:80"
    depends_on:
        - sql

  sql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sql_server2019
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password
